Repository etclabscore/pristine, pull requests merged in 2019-04, with the labels that each got.

#35 fix(building): add definitions section
  BUILDING.md
Labels: bug, enhancement

#34 feat: update release to be more specific
  RELEASING.md
Labels: enhancement

#37 fix(building): remove unneeded definitions
  BUILDING.md
Labels: bug

#40 fix: remove unused jenkins and testing files
  Jenkinsfile
  TESTING.md
Labels: bug

#39 fix: extra backtick
  BUILDING.md
Labels: bug

#36 fix: conventional commits typo
  CONTRIBUTING.md
Labels: bug
